    //I want the atributes to auto fill out the DT, Base Movemet, the armor should also uto change the attributes associated with it 
//Also the lbs to be auto calculated

/*

*/


//Armor and shileds by clicking the armors box the current attribute scoer will be modified

//eventually write a list section that will automatcialy modify the attributes anf FS of the diffrent items
function vigCal (var) {
var VigorScore (){
getelementbyid

}

}


/*Deck rank Modifiers addes to all attributes
    0 to 6 +0
    7 - 12 +1
    13 - 18 +2
    19 -24 +3


/*
    Plasma 
        BodyScore += 4
        FatiugeScore += 4
    Cosmos 
        FocusScore += 1 
    Æther   
        AcuityScore += 1   
    Entropy 
        MettleScore += 1
    Star 
        +1 to talent of choice, 
        ahnk += 1

Core stats
    BodyScore = AgilityScore + AcuityScore + MettleScore + VigorScore + FocusScore + BodyModifiers
    MovementScore = AgilityScore  + BaseMovement + MoveModifier
    InitiavtieScore = AgilityScore + AcuityScore + IntiativeModifier
    DTSCore = MettleScore + AgilityScore + AcuityScore +MettleScore
    SuprisedDTScore= MettleScore + AcuityScore + SurpisedDTModifier
    FatiugeScore = VigorScore + MettleScore + FatiugeModifier
    

Species Modifiers
    Anubi
        Size 5 -1DT StandardDT
        +1 to VigorScore Score 
        Encumberance = vigor X 50
        Bast Movement + 6
        add weapon claws vigor + 1W + rank modifier light modifier
    Menkha
        Size 3 +1 DT StandardDT
        +1 to MettleScore 
        Encumberance = vigor X 65
        Bast Movement + 2
        +2 FS to Climb SKill
        add weapon Horns Mettle +2 Concusive Damage + rank modifier
    Bast 
        Size 4
        +1 to AgilityScore Score 
        Encumberance = vigor X 45
        Bast Movement + 3
    if Human 
        Size 4
        Encumberance = vigor X 45
        Bast Movement + 4
Weapons 

Armor
    Scout 
    Combat -2 to current Agility score
    Juggernaught -4 to current Agillity score
shileds
    Buckler
    Combat -1 to current Agility
    Line -2 to Current Agility
Skills
    When the Realm is Selected then the skills avalible in  that realm are avilible on the drop down list, the attribute will then list the Character's current attribute score the skills level will add any modifiers asociated with it to the corrsponding stats and FS modifiers will be automaticaly calculated from other skills.
items
    Sum of all Lbs
    */